version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - prealloc
    - depguard
    - dupl
    - funlen
    - gochecknoinits
    - gosec
    - lll